import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { DcIconComponent } from '../icons/dc-icon.component';

export type IconStatus = 'same' | 'renamed' | 'custom';

export interface IconEntry {
  id: number;
  uiKit: string;
  lucide: string | null;
  status: IconStatus;
  note?: string;
  figmaImg?: string;
}

export const ICON_MAP: IconEntry[] = [
  {
    id: 1,
    uiKit: 'arrow-up',
    lucide: 'arrow-up',
    status: 'same',
    figmaImg: '/images/arrow-up.svg',
  },
  {
    id: 2,
    uiKit: 'arrow-down',
    lucide: 'arrow-down',
    status: 'same',
    figmaImg: '/images/arrow-down.svg',
  },
  {
    id: 3,
    uiKit: 'arrow-left',
    lucide: 'arrow-left',
    status: 'same',
    figmaImg: '/images/arrow-left.svg',
  },
  {
    id: 4,
    uiKit: 'arrow-right',
    lucide: 'arrow-right',
    status: 'same',
    figmaImg: '/images/arrow-right.svg',
  },
  {
    id: 5,
    uiKit: 'chevron-up',
    lucide: 'chevron-up',
    status: 'same',
    figmaImg: '/images/chevron-up.svg',
  },
  {
    id: 6,
    uiKit: 'chevron-down',
    lucide: 'chevron-down',
    status: 'same',
    figmaImg: '/images/chevron-down.svg',
  },
  {
    id: 7,
    uiKit: 'chevron-left',
    lucide: 'chevron-left',
    status: 'same',
    figmaImg: '/images/chevron-left.svg',
  },
  {
    id: 8,
    uiKit: 'chevron-right',
    lucide: 'chevron-right',
    status: 'same',
    figmaImg: '/images/chevron-right.svg',
  },
  {
    id: 9,
    uiKit: 'chevron-first',
    lucide: 'chevron-first',
    status: 'same',
    figmaImg: '/images/chevron-first.svg',
  },
  {
    id: 10,
    uiKit: 'chevron-last',
    lucide: 'chevron-last',
    status: 'same',
    figmaImg: '/images/chevron-last.svg',
  },
  {
    id: 11,
    uiKit: 'add',
    lucide: 'plus',
    status: 'renamed',
    figmaImg: '/images/add.svg',
  },
  {
    id: 12,
    uiKit: 'check',
    lucide: 'check',
    status: 'same',
    figmaImg: '/images/check.svg',
  },
  {
    id: 13,
    uiKit: 'x',
    lucide: 'x',
    status: 'same',
    figmaImg: '/images/x.svg',
  },
  {
    id: 14,
    uiKit: 'edit',
    lucide: 'pencil',
    status: 'same',
    figmaImg: '/images/edit.svg',
  },
  {
    id: 15,
    uiKit: 'trash',
    lucide: 'trash',
    status: 'same',
    figmaImg: '/images/trash.svg',
  },
  {
    id: 16,
    uiKit: 'delete',
    lucide: 'trash-2',
    status: 'same',
    figmaImg: '/images/delete.svg',
  },
  {
    id: 17,
    uiKit: 'search',
    lucide: 'search',
    status: 'same',
    figmaImg: '/images/search.svg',
  },
  {
    id: 18,
    uiKit: 'zoom-in',
    lucide: 'zoom-in',
    status: 'same',
    figmaImg: '/images/zoom-in.svg',
  },
  {
    id: 19,
    uiKit: 'zoom-out',
    lucide: 'zoom-out',
    status: 'same',
    figmaImg: '/images/zoom-out.svg',
  },
  {
    id: 20,
    uiKit: 'reset-zoom',
    lucide: 'search-x',
    status: 'renamed',
    figmaImg: '/images/reset-zoom.svg',
  },
  {
    id: 21,
    uiKit: 'filter',
    lucide: 'funnel',
    status: 'renamed',
    figmaImg: '/images/filter.svg',
  },
  {
    id: 22,
    uiKit: 'sliders',
    lucide: 'sliders-horizontal',
    status: 'same',
    figmaImg: '/images/sliders.svg',
  },
  {
    id: 23,
    uiKit: 'reorder',
    lucide: 'arrow-down-up',
    status: 'renamed',
    note: 'proposal: list-chevrons-up-down',
    figmaImg: '/images/reorder.svg',
  },
  {
    id: 24,
    uiKit: 'move',
    lucide: 'move',
    status: 'same',
    figmaImg: '/images/move.svg',
  },
  {
    id: 25,
    uiKit: 'expand',
    lucide: 'expand',
    status: 'same',
    figmaImg: '/images/expand.svg',
  },
  {
    id: 26,
    uiKit: 'shrink',
    lucide: 'shrink',
    status: 'same',
    figmaImg: '/images/shrink.svg',
  },
  {
    id: 27,
    uiKit: 'expand-horizontal',
    lucide: 'arrow-left-right',
    status: 'same',
    figmaImg: '/images/expand-horizontal.svg',
  },
  {
    id: 28,
    uiKit: 'expand-vertical',
    lucide: 'arrow-up-down',
    status: 'same',
    figmaImg: '/images/expand-vertical.svg',
  },
  {
    id: 29,
    uiKit: 'copy',
    lucide: 'copy',
    status: 'same',
    figmaImg: '/images/copy.svg',
  },
  {
    id: 30,
    uiKit: 'subtract',
    lucide: 'minus',
    status: 'renamed',
    figmaImg: '/images/subtract.svg',
  },
  {
    id: 31,
    uiKit: 'blocked',
    lucide: 'ban',
    status: 'renamed',
    figmaImg: '/images/blocked.svg',
  },
  {
    id: 32,
    uiKit: 'cancel',
    lucide: 'circle-x',
    status: 'renamed',
    figmaImg: '/images/cancel.svg',
  },
  {
    id: 33,
    uiKit: 'checkmark',
    lucide: 'circle-check',
    status: 'renamed',
    figmaImg: '/images/checkmark.svg',
  },
  {
    id: 34,
    uiKit: 'importance',
    lucide: 'circle-alert',
    status: 'renamed',
    figmaImg: '/images/importance.svg',
  },
  {
    id: 35,
    uiKit: 'reset',
    lucide: 'rotate-ccw',
    status: 'renamed',
    figmaImg: '/images/reset.svg',
  },
  {
    id: 36,
    uiKit: 'file',
    lucide: 'file',
    status: 'same',
    figmaImg: '/images/file.svg',
  },
  {
    id: 37,
    uiKit: 'folder',
    lucide: 'folder',
    status: 'same',
    figmaImg: '/images/folder.svg',
  },
  {
    id: 38,
    uiKit: 'save',
    lucide: 'save',
    status: 'same',
    figmaImg: '/images/save.svg',
  },
  {
    id: 39,
    uiKit: 'download',
    lucide: 'download',
    status: 'same',
    figmaImg: '/images/download.svg',
  },
  {
    id: 40,
    uiKit: 'upload',
    lucide: 'upload',
    status: 'same',
    figmaImg: '/images/upload.svg',
  },
  {
    id: 41,
    uiKit: 'import',
    lucide: 'log-in',
    status: 'renamed',
    figmaImg: '/images/import.svg',
  },
  {
    id: 42,
    uiKit: 'export',
    lucide: 'log-out',
    status: 'renamed',
    figmaImg: '/images/export.svg',
  },
  {
    id: 43,
    uiKit: 'bill',
    lucide: 'file-text',
    status: 'same',
    figmaImg: '/images/bill.svg',
  },
  {
    id: 44,
    uiKit: 'notes',
    lucide: 'sticky-note',
    status: 'same',
    figmaImg: '/images/notes.svg',
  },
  {
    id: 45,
    uiKit: 'tray',
    lucide: 'inbox',
    status: 'renamed',
    figmaImg: '/images/tray.svg',
  },
  {
    id: 46,
    uiKit: 'saved-changes',
    lucide: 'save',
    status: 'renamed',
    figmaImg: '/images/saved-changes.svg',
  },
  {
    id: 47,
    uiKit: 'unsaved-changes',
    lucide: 'save-off',
    status: 'renamed',
    figmaImg: '/images/unsaved-changes.svg',
  },
  {
    id: 48,
    uiKit: 'file-export-pdf',
    lucide: 'file-chart-column',
    status: 'renamed',
    figmaImg: '/images/file-export-pdf.svg',
  },
  {
    id: 49,
    uiKit: 'file-export-xls',
    lucide: 'file-spreadsheet',
    status: 'renamed',
    figmaImg: '/images/file-export-xls.svg',
  },
  {
    id: 50,
    uiKit: 'file-export-qtx',
    lucide: 'file-braces',
    status: 'renamed',
    figmaImg: '/images/file-export-qtx.svg',
  },
  {
    id: 51,
    uiKit: 'save-in-progress',
    lucide: 'save-all',
    status: 'renamed',
    figmaImg: '/images/save-in-progress.svg',
  },
  {
    id: 52,
    uiKit: 'home',
    lucide: 'house',
    status: 'renamed',
    figmaImg: '/images/home.svg',
  },
  {
    id: 53,
    uiKit: 'menu-grid',
    lucide: 'layout-grid',
    status: 'same',
    figmaImg: '/images/menu-grid.svg',
  },
  {
    id: 54,
    uiKit: 'list',
    lucide: 'list',
    status: 'same',
    figmaImg: '/images/list.svg',
  },
  {
    id: 55,
    uiKit: 'hierarchy',
    lucide: 'network',
    status: 'renamed',
    figmaImg: '/images/hierarchy.svg',
  },
  {
    id: 56,
    uiKit: 'more',
    lucide: 'ellipsis',
    status: 'renamed',
    figmaImg: '/images/more.svg',
  },
  {
    id: 57,
    uiKit: 'login',
    lucide: 'log-in',
    status: 'same',
    figmaImg: '/images/login.svg',
  },
  {
    id: 58,
    uiKit: 'logout',
    lucide: 'log-out',
    status: 'same',
    figmaImg: '/images/logout.svg',
  },
  {
    id: 59,
    uiKit: 'enter',
    lucide: 'corner-down-left',
    status: 'same',
    figmaImg: '/images/enter.svg',
  },
  {
    id: 60,
    uiKit: 'avatar',
    lucide: 'user',
    status: 'renamed',
    figmaImg: '/images/avatar.svg',
  },
  {
    id: 61,
    uiKit: 'people',
    lucide: 'users',
    status: 'renamed',
    figmaImg: '/images/people.svg',
  },
  {
    id: 62,
    uiKit: 'group',
    lucide: 'users-round',
    status: 'same',
    figmaImg: '/images/group.svg',
  },
  {
    id: 63,
    uiKit: 'message',
    lucide: 'message-square',
    status: 'same',
    figmaImg: '/images/message.svg',
  },
  {
    id: 64,
    uiKit: 'message-text',
    lucide: 'message-square-text',
    status: 'same',
    figmaImg: '/images/message-text.svg',
  },
  {
    id: 65,
    uiKit: 'send',
    lucide: 'send',
    status: 'same',
    figmaImg: '/images/send.svg',
  },
  {
    id: 66,
    uiKit: 'bell',
    lucide: 'bell',
    status: 'same',
    figmaImg: '/images/bell.svg',
  },
  {
    id: 67,
    uiKit: 'info',
    lucide: 'info',
    status: 'same',
    figmaImg: '/images/info.svg',
  },
  {
    id: 68,
    uiKit: 'help',
    lucide: 'circle-question-mark',
    status: 'renamed',
    figmaImg: '/images/help.svg',
  },
  {
    id: 69,
    uiKit: 'alert',
    lucide: 'triangle-alert',
    status: 'renamed',
    figmaImg: '/images/alert.svg',
  },
  {
    id: 70,
    uiKit: 'thumbs-up',
    lucide: 'thumbs-up',
    status: 'same',
    figmaImg: '/images/thumbs-up.svg',
  },
  {
    id: 71,
    uiKit: 'thumbs-down',
    lucide: 'thumbs-down',
    status: 'same',
    figmaImg: '/images/thumbs-down.svg',
  },
  {
    id: 72,
    uiKit: 'star',
    lucide: 'star',
    status: 'same',
    figmaImg: '/images/star.svg',
  },
  {
    id: 73,
    uiKit: 'heart',
    lucide: 'heart',
    status: 'same',
    figmaImg: '/images/heart.svg',
  },
  {
    id: 74,
    uiKit: 'history',
    lucide: 'history',
    status: 'same',
    figmaImg: '/images/history.svg',
  },
  {
    id: 75,
    uiKit: 'gear',
    lucide: 'settings',
    status: 'renamed',
    figmaImg: '/images/gear.svg',
  },
  {
    id: 76,
    uiKit: 'tools',
    lucide: 'wrench',
    status: 'renamed',
    figmaImg: '/images/tools.svg',
  },
  {
    id: 77,
    uiKit: 'key',
    lucide: 'key',
    status: 'same',
    figmaImg: '/images/key.svg',
  },
  {
    id: 78,
    uiKit: 'camera',
    lucide: 'camera',
    status: 'same',
    figmaImg: '/images/camera.svg',
  },
  {
    id: 79,
    uiKit: 'eye',
    lucide: 'eye',
    status: 'same',
    figmaImg: '/images/eye.svg',
  },
  {
    id: 80,
    uiKit: 'eye_disabled',
    lucide: 'eye-off',
    status: 'same',
    figmaImg: '/images/eye_disabled.svg',
  },
  {
    id: 81,
    uiKit: 'print',
    lucide: 'printer',
    status: 'same',
    figmaImg: '/images/print.svg',
  },
  {
    id: 82,
    uiKit: 'computer',
    lucide: 'monitor',
    status: 'renamed',
    figmaImg: '/images/computer.svg',
  },
  {
    id: 83,
    uiKit: 'mobile',
    lucide: 'smartphone',
    status: 'renamed',
    figmaImg: '/images/mobile.svg',
  },
  {
    id: 84,
    uiKit: 'calendar',
    lucide: 'calendar',
    status: 'same',
    figmaImg: '/images/calendar.svg',
  },
  {
    id: 85,
    uiKit: 'cycle',
    lucide: 'refresh-cw',
    status: 'same',
    figmaImg: '/images/cycle.svg',
  },
  {
    id: 86,
    uiKit: 'chart',
    lucide: 'chart-column-big',
    status: 'renamed',
    figmaImg: '/images/chart.svg',
  },
  {
    id: 87,
    uiKit: 'gauge',
    lucide: 'gauge',
    status: 'same',
    figmaImg: '/images/gauge.svg',
  },
  {
    id: 88,
    uiKit: 'selection',
    lucide: 'rectangle-horizontal',
    status: 'same',
    figmaImg: '/images/selection.svg',
  },
  {
    id: 89,
    uiKit: 'crosshairs',
    lucide: 'crosshair',
    status: 'same',
    figmaImg: '/images/crosshairs.svg',
  },
  {
    id: 90,
    uiKit: 'layers',
    lucide: 'layers',
    status: 'same',
    figmaImg: '/images/layers.svg',
  },
  {
    id: 91,
    uiKit: 'circle',
    lucide: 'circle',
    status: 'same',
    figmaImg: '/images/circle.svg',
  },
  {
    id: 92,
    uiKit: 'dollar',
    lucide: 'dollar-sign',
    status: 'same',
    figmaImg: '/images/dollar.svg',
  },
  {
    id: 93,
    uiKit: 'euro',
    lucide: 'euro',
    status: 'same',
    figmaImg: '/images/euro.svg',
  },
  {
    id: 94,
    uiKit: 'pound',
    lucide: 'pound-sterling',
    status: 'same',
    figmaImg: '/images/pound.svg',
  },
  {
    id: 95,
    uiKit: 'yen',
    lucide: 'japanese-yen',
    status: 'same',
    figmaImg: '/images/yen.svg',
  },
  {
    id: 96,
    uiKit: 'cloud',
    lucide: 'cloud',
    status: 'same',
    figmaImg: '/images/cloud.svg',
  },
  {
    id: 97,
    uiKit: 'globe',
    lucide: 'globe',
    status: 'same',
    figmaImg: '/images/globe.svg',
  },
  {
    id: 98,
    uiKit: 'shield',
    lucide: 'shield',
    status: 'same',
    figmaImg: '/images/shield.svg',
  },
  {
    id: 99,
    uiKit: 'text',
    lucide: 'text-align-start',
    status: 'renamed',
    figmaImg: '/images/text.svg',
  },
  {
    id: 100,
    uiKit: 'swatches',
    lucide: 'swatch-book',
    status: 'renamed',
    figmaImg: '/images/swatches.svg',
  },
  {
    id: 101,
    uiKit: 'palette',
    lucide: 'palette',
    status: 'same',
    figmaImg: '/images/palette.svg',
  },
  {
    id: 102,
    uiKit: 'bucket',
    lucide: 'paint-bucket',
    status: 'same',
    figmaImg: '/images/bucket.svg',
  },
  {
    id: 103,
    uiKit: 'confetti',
    lucide: 'party-popper',
    status: 'renamed',
    figmaImg: '/images/confetti.svg',
  },
  {
    id: 104,
    uiKit: 'curves',
    lucide: 'chart-spline',
    status: 'renamed',
    figmaImg: '/images/curves.svg',
  },
  {
    id: 105,
    uiKit: 'drop',
    lucide: 'droplet',
    status: 'same',
    figmaImg: '/images/drop.svg',
  },
  {
    id: 106,
    uiKit: 'dropper',
    lucide: 'pipette',
    status: 'same',
    figmaImg: '/images/dropper.svg',
  },
  {
    id: 107,
    uiKit: 'question',
    lucide: 'circle-question-mark',
    status: 'renamed',
    figmaImg: '/images/question.svg',
  },
  {
    id: 108,
    uiKit: 'add-grid',
    lucide: 'grid-2x2-plus',
    status: 'renamed',
    figmaImg: '/images/add-grid.svg',
  },
  {
    id: 109,
    uiKit: 'add-stack',
    lucide: 'layers-plus',
    status: 'renamed',
    figmaImg: '/images/add-stack.svg',
  },
  {
    id: 110,
    uiKit: 'search-folder',
    lucide: 'folder-search',
    status: 'same',
    figmaImg: '/images/search-folder.svg',
  },
  {
    id: 111,
    uiKit: 'leaf',
    lucide: 'leaf',
    status: 'same',
    figmaImg: '/images/leaf.svg',
  },
  {
    id: 112,
    uiKit: 'seat',
    lucide: 'contact',
    status: 'renamed',
    figmaImg: '/images/seat.svg',
  },
  {
    id: 113,
    uiKit: 'not-dispense',
    lucide: 'droplet-off',
    status: 'renamed',
    figmaImg: '/images/not-dispense.svg',
  },
  {
    id: 114,
    uiKit: 'color-batch',
    lucide: 'panel-top-bottom-dashed',
    status: 'renamed',
    figmaImg: '/images/color-batch.svg',
  },
  {
    id: 115,
    uiKit: 'color-sample',
    lucide: 'compass',
    status: 'renamed',
    figmaImg: '/images/color-sample.svg',
  },
  {
    id: 116,
    uiKit: 'color-standard',
    lucide: 'box',
    status: 'renamed',
    figmaImg: '/images/color-standard.svg',
  },
  {
    id: 117,
    uiKit: 'instrument-measure',
    lucide: 'circle-gauge',
    status: 'renamed',
    figmaImg: '/images/instrument-measure.svg',
  },
  {
    id: 118,
    uiKit: 'instrument-connected',
    lucide: 'cast',
    status: 'renamed',
    figmaImg: '/images/instrument-connected.svg',
  },
  {
    id: 119,
    uiKit: 'instrument-disconnected',
    lucide: 'unplug',
    status: 'renamed',
    figmaImg: '/images/instrument-disconnected.svg',
  },

  {
    id: 123,
    uiKit: 'standard',
    lucide: 'award',
    status: 'renamed',
    figmaImg: '/images/standard.svg',
  },
];

@Component({
  selector: 'app-icon-map',
  imports: [RouterLink, DcIconComponent],
  templateUrl: './icon-map.html',
  styleUrl: './icon-map.less',
})
export class IconMap {
  protected readonly icons = ICON_MAP;
  protected activeFilter: IconStatus | 'all' = 'all';

  protected get filtered(): IconEntry[] {
    if (this.activeFilter === 'all') return this.icons;
    return this.icons.filter((i) => i.status === this.activeFilter);
  }

  protected counts = {
    all: ICON_MAP.length,
    same: ICON_MAP.filter((i) => i.status === 'same').length,
    renamed: ICON_MAP.filter((i) => i.status === 'renamed').length,
    custom: ICON_MAP.filter((i) => i.status === 'custom').length,
  };
}
